version: "3.8"

services:
  auth-service:
    build: ./auth-service
    ports:
      - "8080:8080"
    env_file:
      - ./auth-service/.env
    depends_on:
      - mongo-auth

  mongo-auth:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongo-auth-data:/data/db

  product-service:
    build: ./product-service
    ports:
      - "8081:8081"
    env_file:
      - ./product-service/.env
    depends_on:
      - mongo-product

  mongo-product:
    image: mongo:6
    ports:
      - "27018:27017"
    volumes:
      - mongo-product-data:/data/db

volumes:
  mongo-auth-data:
  mongo-product-data:
