# version: "3"

services:
  gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - auth-service
      - product-service
      - order-service

  auth-service:
    build: ./auth-services
    container_name: auth-services
    ports:
      - "8081:8081"
    env_file:
      - ./auth-services/.env
    depends_on:
      - mongo-auth

  product-service:
    build: ./product-service
    container_name: product-service
    ports:
      - "8082:8082"
    env_file:
      - ./product-service/.env
    depends_on:
      - mongo-product
  order-service:
    build: ./order-service
    container_name: order-service
    ports:
      - "8083:8083"
    env_file:
      - ./order-service/.env
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    environment:
      PGHOST: postgres 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ordersdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongo-auth:
    image: mongo
    container_name: mongo-auth
    ports:
      - "27017:27017"
    volumes:
      - mongo-auth-data:/data/db

  mongo-product:
    image: mongo
    container_name: mongo-product
    ports:
      - "27018:27017"
    volumes:
      - mongo-product-data:/data/db

volumes:
  mongo-auth-data:
  mongo-product-data:
  postgres_data:



